version: "3.9"

services:
    web:
        container_name: nginx-nostradamus
        image: nginx:latest
        ports:
            - "${NGINX_PORT:-80}:80"
        volumes:
            - ./:/var/www/html
            - "./docker/web/${APP_ENV:-local}_default.conf:/etc/nginx/conf.d/default.conf"

        links:
            - php-fpm
            - mysql

    php-fpm:
        container_name: php-nostradamus
        build:
          dockerfile: docker/php/Dockerfile
          context: .

        volumes:
            - ./:/var/www/html
        links:
            - mysql
    mysql:
        container_name: db-nostradamus
        image: mariadb:10.3
        ports:
            - "${DOCKER_DB_PORT:-3306}:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}
            - MYSQL_DATABASE=nostradamus
        restart: always

    frontend:
        container_name: front-nostradamus
        image: node:lts
        working_dir: /var/www/html
        entrypoint: /bin/bash
        environment:
            - VITE_PROJECT_ID=${VITE_PROJECT_ID:-0ea9e18eb6629f920529476cc5cb9ad5}
        ports:
           - "8000:8000"
        volumes:
            - ./:/var/www/html
        tty: true

